dashboard/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='dashboard'),
    path('scoring/', views.scoring, name='scoring'),
    path('scoring/<int:appid>', views.score_applicant, name='score_applicant'),
    path('rubric/', views.rubric, name='rubric'),
    path('teams/', views.teams, name='teams'),
    path('teams/<int:teamid>', views.specific_team, name='specific_team'),
    path('mentors/', views.mentors, name='mentors'),
    path('proposal/', views.ProjectProposalCreate.as_view(), name='proposal'),
    path('documentation/success/', views.documentation_success, name='documentation_success'),
    path('milestones/', views.MilestoneCreate.as_view(), name='milestone'),
    path('workshops/', views.workshops, name='workshop'),
    path('calendar/', views.calendar, name="calendar"),
]

ieeeqpucsd/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('ieeeqpadmin/', admin.site.urls),
    path('', include('landing.urls')),
    path('dashboard/', include('dashboard.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

landing/urls.py
from django.urls import path
from . import views
from datetime import date

deadline = date(2020, 1, 15)
today = date.today()

if (today >= deadline):
    application_view = views.apply_closed
else:
    application_view = views.QPApplicationCreate.as_view()

urlpatterns = [
    path('', views.index, name='index'),
    path('apply/', application_view, name='apply'),
    path('success/', views.apply_success, name='apply-success'),
    path('login/', views.login_view, name='login'),
    path('ieeeqpsignup/', views.register_view, name='register'),
    path('logout/', views.logout_view, name='logout'),
    # path('.well-known/acme-challenge/579nh20yWm02orHMdz28CwPMtC8QWlMOjNEjIz8b9T4/', views.https_view, name='https'),
]

dashboard/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.contrib.auth.models import User
from landing.models import QPApplication, team

class ScoreApplication(models.Model):
    application = models.ForeignKey(QPApplication, on_delete=models.DO_NOTHING)
    scorer = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    score = models.IntegerField(default=0, validators=[MaxValueValidator(10), MinValueValidator(0)])

class ProjectProposal(models.Model):
    title = models.CharField(max_length=100, help_text="Project Title")
    description = models.CharField(max_length=2000, help_text="Project Description")
    team_num = models.CharField(max_length=100, help_text="Team Number")
    team = models.CharField(max_length=300, help_text="Team Nickname")

    PROGRAM_CHOICES = (
        ('qp', 'QP'),
        ('qp2', 'QP++'),
    )

    program = models.CharField(
        max_length=50,
        choices=PROGRAM_CHOICES,
        default='qp',
        help_text='Program (QP or QP++)',
    )

    materials = models.CharField(max_length=2000, help_text="Bill of Materials (Enter a new line for every item. Please provide: name, quantity, vendor-link for each)")
    timeline = models.CharField(max_length=2000, help_text="Timeline of Work (Enter a new line for every week. Please provide: week # and task description for each)")
    confidence = models.CharField(max_length=2000, help_text="Collect a sentence from each member stating why you are confident you will succeed in making this project")

class Milestone(models.Model):
    REPORT_NUM_CHOICES = (
        ('1', 'Week 5'),
        ('2', 'Week 7'),
    )

    report_num = models.CharField(
        max_length=50,
        choices=REPORT_NUM_CHOICES,
        default='2',
        help_text='Choose a milestone report',
    )

    team_num = models.IntegerField(help_text="Team Number (Please enter a number from 1 - 113)")

    PROGRAM_CHOICES = (
        ('qp', 'QP'),
        ('qp2', 'QP++'),
    )

    program = models.CharField(
        max_length=50,
        choices=PROGRAM_CHOICES,
        default='qp',
        help_text='Program (QP or QP++)',
    )

    accomplishments = models.CharField(max_length=2000, help_text="What have you accomplished so far?")
    projected = models.CharField(max_length=2000, help_text="What do you hope to accomplish in the next 2 weeks?")
    blockers = models.CharField(max_length=2000, null=True, blank=True, help_text="Name a few issues that are hindering/preventing your progress (Leave blank if none)")

dashboard/forms.py
from django import forms
from dashboard.models import ScoreApplication, ProjectProposal, Milestone
from landing.models import QPApplication, team
from django.forms import models, Textarea, fields

class AdvancedModelChoiceIterator(models.ModelChoiceIterator):
    def choice(self, obj):
        return (self.field.prepare_value(obj), obj)

class AdvancedModelChoiceField(models.ModelMultipleChoiceField):
    def _get_choices(self):
        if hasattr(self, '_choices'):
            return self._choices
        return AdvancedModelChoiceIterator(self)
    
    choices = property(_get_choices, fields.MultipleChoiceField._set_choices)

class ScoreApplicationForm(forms.ModelForm):
    score = forms.IntegerField()

    class Meta:
        model = ScoreApplication
        fields = [
            'score',
        ]

    def clean(self, *args, **kwargs):
        score = self.cleaned_data.get('score')
        if  score is None or score < 0 or score > 10:
            raise forms.ValidationError("Please enter a score between 1 and 10!")
        return super(ScoreApplicationForm, self).clean(*args, **kwargs)

class ProjectProposalForm(forms.ModelForm):
    class Meta:
        model = ProjectProposal
        fields = '__all__'
        widgets = {
          'description': Textarea(attrs={'rows':8, 'cols':50}),
          'materials': Textarea(attrs={'rows':8, 'cols':50}),
          'timeline': Textarea(attrs={'rows':8, 'cols':50}),
          'confidence': Textarea(attrs={'rows':8, 'cols':50}),
        }

class MilestoneReportForm(forms.ModelForm):
    class Meta:
        model = Milestone
        fields = '__all__'
        widgets = {
          'accomplishments': Textarea(attrs={'rows':8, 'cols':50}),
          'projected': Textarea(attrs={'rows':8, 'cols':50}),
          'blockers': Textarea(attrs={'rows':8, 'cols':50}),
        }

class UpdateQPApplication(forms.ModelForm):
    class Meta:
        model = QPApplication
        fields = [
            'accepted'
        ]

class CreateTeamForm(forms.ModelForm):
    # using the above customized ModelChoiceField here
    member_choices = AdvancedModelChoiceField(
        widget = forms.CheckboxSelectMultiple,
        queryset = QPApplication.objects.all(),
        required = False,
        help_text = 'Add members to this team'
    )

    def customSave(self):
        teams_json = []
        create_team = self.save(commit=False)
        cleaned_members = self.cleaned_data['member_choices']
        for member in cleaned_members:
            teams_json.append(member.first_name + ' ' + member.last_name)

        create_team.members = teams_json
        create_team.save()
        return create_team

    class Meta:
        model = team
        fields = [
            'name',
            'nickname',
        ]

dashboard/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from landing.models import QPApplication, team
from dashboard.models import ScoreApplication, ProjectProposal, Milestone
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from ieeeqpucsd import settings
from itertools import chain
from . import forms
import os

# @login_required
def index(request):
    return render(request, 'dashboard.html', context={})

#(LoginRequiredMixin, CreateView)
class ProjectProposalCreate(CreateView):
    model = ProjectProposal
    form_class = forms.ProjectProposalForm

    def get_success_url(self):
        return reverse('documentation_success')

    def get_context_data(self, **kwargs):
        ctx = super(ProjectProposalCreate, self).get_context_data(**kwargs)
        ctx['proposals_qp'] = ProjectProposal.objects.filter(program="qp").order_by('id')
        ctx['proposals_qp2'] = ProjectProposal.objects.filter(program="qp2").order_by('id')
        return ctx

#(LoginRequiredMixin, CreateView)
class MilestoneCreate(CreateView):
    model = Milestone
    form_class = forms.MilestoneReportForm

    def get_success_url(self):
        return reverse('documentation_success')

    def get_context_data(self, **kwargs):
        ctx = super(MilestoneCreate, self).get_context_data(**kwargs)
        ctx['milestone_1'] = Milestone.objects.filter(report_num='1').order_by('id')
        ctx['milestone_2'] = Milestone.objects.filter(report_num='2').order_by('id')
        return ctx

# @login_required
def documentation_success(request):
    return render(request, 'documentation_success.html', context={})

# @login_required
@user_passes_test(lambda u: u.has_perm('landing.can_score_applicant'))
def scoring(request):
    existing_ids = ScoreApplication.objects.filter(scorer_id=request.user.id).values_list('application_id', flat=True)
    existing_apps = QPApplication.objects.filter(id__in=existing_ids)
    unscored_apps = QPApplication.objects.exclude(id__in=existing_ids)

    context={
        'unscored_apps': unscored_apps,
        'existing_apps': existing_apps,
        'all_apps': QPApplication.objects.all().count,
    }
    return render(request, 'scoring.html', context)

# @login_required
@user_passes_test(lambda u: u.has_perm('landing.can_score_applicant'))
def rubric(request):
    return render(request, 'dash_rubric.html', context={})

# @login_required
@user_passes_test(lambda u: u.has_perm('landing.can_score_applicant'))
def score_applicant(request, appid):
    instance = get_object_or_404(QPApplication, id=appid)
    existing = ScoreApplication.objects.filter(scorer_id=request.user.id, application_id=instance.id)
    check_existing = existing and existing.count() > 0

    if request.method == "POST":
        update_form = forms.UpdateQPApplication(request.POST, instance=instance)
        score_form = forms.ScoreApplicationForm(request.POST)
        safe_num_scores = instance.num_of_scores if instance.num_of_scores else 0
        safe_score = instance.score if instance.score else 0

        if score_form.is_valid() and update_form.is_valid():
            post_score = score_form.save(commit=False)
            post_application = update_form.save(commit=False)
            post_score.application_id = instance.id
            post_score.scorer_id = request.user.id
            post_application.num_of_scores = safe_num_scores + 1
            cleaned_score = score_form.cleaned_data.get('score')
            cleaned_accept = update_form.cleaned_data.get('accepted')
            post_application.score = cleaned_score + safe_score
            if (cleaned_accept):
                post_application.accepted = cleaned_accept
            else:
                post_application.accepted = instance.accepted
            post_score.save()
            post_application.save()
            return redirect('scoring')
        
        if not score_form.is_valid() and update_form.is_valid():
            update_form.save()
    
    else:
        update_form = forms.UpdateQPApplication(instance=instance)
        score_form = forms.ScoreApplicationForm()

    context={
        'applicant': instance,
        'score_form': score_form,
        'update_form': update_form,
        'check_existing': check_existing,
    }

    return render(request, 'score_applicant.html', context)

@login_required
def teams(request):
    if request.method == "POST":
        create_team = forms.CreateTeamForm(request.POST)
        if create_team.is_valid():
            cleaned_members = create_team.cleaned_data['member_choices']
            custom_saved_members = create_team.customSave()

            for member in cleaned_members:
                app_instance = get_object_or_404(QPApplication, id=member.id)
                update_form = forms.UpdateQPApplication(request.POST, instance=app_instance)
                post_application = update_form.save(commit=False)
                post_application.team_id = custom_saved_members.pk
                post_application.accepted=1
                post_application.save()

            return redirect('teams')
    else:
        create_team = forms.CreateTeamForm()
    
    qpteams = {}
    qp2teams = {}
    
    context = {
        'create_team': create_team,
        'qpteams': team.objects.filter(nickname="QP").order_by('id'),
        'qp2teams': team.objects.filter(nickname="QP++").order_by('id'),
    }

    return render(request, 'teams.html', context)

@login_required
def specific_team(request, teamid):
    # Get specific team using id
    team_instance = get_object_or_404(team, id=teamid)

    # Backfilling
    backfill_members = team_instance.members.replace("['", "").replace("']", "").split("', '")

    # Assign team id to each person on team
    for member in backfill_members:
        name = member.split(" ", 1)
        person = QPApplication.objects.filter(first_name=name[0]).filter(last_name=name[1]).first()
        update_form = forms.UpdateQPApplication(request.POST, instance=person)
        post_application = update_form.save(commit=False)
        post_application.team_id = teamid
        post_application.accepted = 1
        post_application.save()

    # Get QPApplicant
    members = QPApplication.objects.filter(team_id=teamid)

    # Get mentor
    mentor = User.objects.filter(id=team_instance.mentor_id)

    # get email
    emails = members.values('email')

    # list of emails
    team_emails = {}
    for i in range(0, len(emails)):
        team_emails[members[i].first_name + ' ' + members[i].last_name] = emails[i]['email']

    context = {
        'team': team_instance,
        'team_emails': team_emails,
        'mentor': mentor,
    }
    return render(request, 'specific_team.html', context)


# @login_required
def mentors(request):
    image_list=[]
    email_list={}
    for root, dirs, files in os.walk(settings.STATIC_ROOT):
        for file in files:
            staticUrl = 'staff/'
            if file.endswith("_mentor.jpg"):
                mentor = User.objects.filter(first_name=file.replace("_mentor.jpg", ""))
                email = mentor.values_list('email', flat=True)
                name = mentor.values_list('first_name', flat=True)
                for i in range(0, len(email)):
                    email_list[name[i]] = email[i]

                staticUrl += file
                image_list.append(staticUrl)
    
    row1 = image_list[0: len(image_list)//4]
    row2 = image_list[len(image_list)//4: len(image_list)//2]
    row3 = image_list[len(image_list)//2: len(image_list)*3//4]
    row4 = image_list[len(image_list)*3//4: len(image_list)]

    return render(request, 'mentors.html', context={ 'row1': row1, 'row2': row2, 'row3': row3, 'row4': row4, 'emails': email_list })

@login_required
def calendar(request):
    return render(request, 'calendar.html', context={})

# @login_required
def workshops(request):
    return render(request, 'workshops.html', context={})

dashboard/templates/dashboard/milestone_form.html
{% extends 'dash_generic.html' %}
{% block body %}

{% load widget_tweaks %}
<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
    <div class="row">
        <ol class="breadcrumb">
            <li><a href="/dashboard">
                    <em class="fa fa-home"></em>
                </a></li>
            <li class="active">Milestone Report</li>
        </ol>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="col-lg-12" style="margin-bottom: 20px;">
                <h1 class="page-header" style="padding: 0;">Milestone
                    Report{% if perms.landing.can_score_applicant %}s{% else %}{% endif %}</h1>
                <p class="text-divider"></p>
                {% if perms.landing.can_score_applicant %}
                <button id="all-btn" type="button" class="btn btn-info">View All</button>
                <button id="week5-btn" type="button" class="btn btn-warning">Week 5</button>
                <button id="week7-btn" type="button" class="btn btn-primary">Week 7</button>
                {% endif %}
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            {% if perms.landing.can_score_applicant %}
            <div id="week5-panels">
                {% for milestone in milestone_1 %}
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="panel panel-warning">
                        <div class="panel-heading dark-overlay">Team {{ milestone.team_num }} -
                            {{ milestone.get_program_display }}</div>
                        <div class="panel-body">
                            <div class="row" style="margin-bottom: 20px;">
                                <div class="col-lg-12">
                                    <h5>Accomplishments</h5>
                                    <div class="col-lg-12">
                                        {{ milestone.accomplishments }}
                                    </div>
                                </div>
                            </div>
                            <div class="row" style="margin-bottom: 20px;">
                                <div class="col-lg-12">
                                    <h5>Estimates</h5>
                                    <div class="col-lg-12">
                                        {{ milestone.projected }}
                                    </div>
                                </div>
                            </div>
                            <div class="row" style="margin-bottom: 20px;">
                                <div class="col-lg-12">
                                    <h5>Blockers</h5>
                                    <div class="col-lg-12">
                                        {{ milestone.blockers }}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            <div id="week7-panels">
                {% for milestone in milestone_2 %}
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="panel panel-info">
                        <div class="panel-heading dark-overlay">Team {{ milestone.team_num }} -
                            {{ milestone.get_program_display }}</div>
                        <div class="panel-body">
                            <div class="row" style="margin-bottom: 20px;">
                                <div class="col-lg-12">
                                    <h5>Accomplishments</h5>
                                    <div class="col-lg-12">
                                        {{ milestone.accomplishments }}
                                    </div>
                                </div>
                            </div>
                            <div class="row" style="margin-bottom: 20px;">
                                <div class="col-lg-12">
                                    <h5>Estimates</h5>
                                    <div class="col-lg-12">
                                        {{ milestone.projected }}
                                    </div>
                                </div>
                            </div>
                            <div class="row" style="margin-bottom: 20px;">
                                <div class="col-lg-12">
                                    <h5>Blockers</h5>
                                    <div class="col-lg-12">
                                        {{ milestone.blockers }}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            {% else %}
            <form method="post" novalidate>
                {% csrf_token %}

                {% for hidden_field in form.hidden_fields %}
                {{ hidden_field }}
                {% endfor %}

                {% if form.non_field_errors %}
                <div class="alert alert-danger" role="alert">
                    {% for error in form.non_field_errors %}
                    {{ error }}
                    {% endfor %}
                </div>
                {% endif %}

                {% for field in form.visible_fields %}
                <br>
                <div class="form-group">
                    <p class="text-white" style="font-size: 20px; letter-spacing: 0.5px;">
                        {% if field.help_text %}{{ field.help_text }}{% else %}{{ field.label_tag }}{% endif %}</p>
                    {% if form.is_bound %}
                    {% if field.errors %}
                    {% render_field field class="form-control is-invalid" %}
                    {% for error in field.errors %}
                    <div class="invalid-feedback">
                        {{ error }}
                    </div>
                    {% endfor %}
                    {% else %}
                    {% render_field field class="form-control is-valid" %}
                    {% endif %}
                    {% else %}
                    {% render_field field class="form-control" %}
                    {% endif %}
                </div>
                <br>
                {% endfor %}
                <div class="col-md-12 text-center">
                    <button type="submit" class="btn btn-info btn-lg"
                        style="color: white !important; border-width: 0px !important;">Submit Report</button>
                </div>
                <br><br><br><br><br><br><br>
            </form>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script>
    $('#week5-btn').click(() => {
        $('#week5-panels').show();
        $('#week7-panels').hide();
    });

    $('#week7-btn').click(() => {
        $('#week5-panels').hide();
        $('#week7-panels').show();
    });

    $('#all-btn').click(() => {
        $('#week5-panels').show();
        $('#week7-panels').show();
    });
</script>
{% endblock %}

dashboard/templates/dashboard/projectproposal_form.html
{% extends 'dash_generic.html' %}
{% block body %}

{% load widget_tweaks %}
<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
  <div class="row">
    <ol class="breadcrumb">
      <li><a href="/dashboard">
          <em class="fa fa-home"></em>
        </a></li>
      <li class="active">Proposal</li>
    </ol>
  </div>

  <div class="row">
    <div class="col-lg-12">
      <div class="col-lg-12" style="margin-bottom: 20px;">
        <h1 class="page-header" style="padding: 0;">Project
          Proposal{% if perms.landing.can_score_applicant %}s{% else %}{% endif %}</h1>
        <p class="text-divider"></p>
        {% if perms.landing.can_score_applicant %}
        <button id="all-btn" type="button" class="btn btn-info">View All</button>
        <button id="qp-btn" type="button" class="btn btn-warning">QP Proposals</button>
        <button id="qp2-btn" type="button" class="btn btn-primary">QP++ Proposals</button>
        {% endif %}
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-12">
      {% if perms.landing.can_score_applicant %}
      <div id="qp-panels">
        {% for proposal in proposals_qp %}
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
          <div class="panel panel-warning">
            <div class="panel-heading dark-overlay">Team {{ proposal.team_num }} - {{ proposal.get_program_display }} ({{ proposal.team }})
            </div>
            <div class="panel-body">
              <div class="row" style="margin-bottom: 20px;">
                <div class="col-lg-12">
                  <h5>Project Title</h5>
                  <div class="col-lg-12">
                    {{ proposal.title }}
                  </div>
                </div>
              </div>
              <div class="row" style="margin-bottom: 20px;">
                <div class="col-lg-12">
                  <h5>Project Description</h5>
                  <div class="col-lg-12">
                    {{ proposal.description }}
                  </div>
                </div>
              </div>
              <div class="row" style="margin-bottom: 20px;">
                <div class="col-lg-12">
                  <h5>Bill of Materials</h5>
                  <div class="col-lg-12">
                    {{ proposal.materials }}
                  </div>
                </div>
              </div>
              <div class="row" style="margin-bottom: 20px;">
                <div class="col-lg-12">
                  <h5>Timeline</h5>
                  <div class="col-lg-12">
                    {{ proposal.timeline }}
                  </div>
                </div>
              </div>
              <div class="row" style="margin-bottom: 20px;">
                <div class="col-lg-12">
                  <h5>Confidence</h5>
                  <div class="col-lg-12">
                    {{ proposal.confidence }}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
      <div id="qp2-panels">
        {% for proposal in proposals_qp2 %}
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
          <div class="panel panel-info">
            <div class="panel-heading dark-overlay">Team {{ proposal.team_num }} - {{ proposal.get_program_display }} ({{ proposal.team }})
            </div>
            <div class="panel-body">
              <div class="row" style="margin-bottom: 20px;">
                <div class="col-lg-12">
                  <h5>Project Title</h5>
                  <div class="col-lg-12">
                    {{ proposal.title }}
                  </div>
                </div>
              </div>
              <div class="row" style="margin-bottom: 20px;">
                <div class="col-lg-12">
                  <h5>Project Description</h5>
                  <div class="col-lg-12">
                    {{ proposal.description }}
                  </div>
                </div>
              </div>
              <div class="row" style="margin-bottom: 20px;">
                <div class="col-lg-12">
                  <h5>Bill of Materials</h5>
                  <div class="col-lg-12">
                    {{ proposal.materials }}
                  </div>
                </div>
              </div>
              <div class="row" style="margin-bottom: 20px;">
                <div class="col-lg-12">
                  <h5>Timeline</h5>
                  <div class="col-lg-12">
                    {{ proposal.timeline }}
                  </div>
                </div>
              </div>
              <div class="row" style="margin-bottom: 20px;">
                <div class="col-lg-12">
                  <h5>Confidence</h5>
                  <div class="col-lg-12">
                    {{ proposal.confidence }}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
      {% else %}
      <form method="post" novalidate>
        {% csrf_token %}

        {% for hidden_field in form.hidden_fields %}
        {{ hidden_field }}
        {% endfor %}

        {% if form.non_field_errors %}
        <div class="alert alert-danger" role="alert">
          {% for error in form.non_field_errors %}
          {{ error }}
          {% endfor %}
        </div>
        {% endif %}

        {% for field in form.visible_fields %}
        <br>
        <div class="form-group">
          <p class="text-white" style="font-size: 20px; letter-spacing: 0.5px;">
            {% if field.help_text %}{{ field.help_text }}{% else %}{{ field.label_tag }}{% endif %}</p>
          {% if form.is_bound %}
          {% if field.errors %}
          {% render_field field class="form-control is-invalid" %}
          {% for error in field.errors %}
          <div class="invalid-feedback">
            {{ error }}
          </div>
          {% endfor %}
          {% else %}
          {% render_field field class="form-control is-valid" %}
          {% endif %}
          {% else %}
          {% render_field field class="form-control" %}
          {% endif %}
        </div>
        <br>
        {% endfor %}
        <div class="col-md-12 text-center">
          <button type="submit" class="btn btn-info btn-lg"
            style="color: white !important; border-width: 0px !important;">Submit Proposal</button>
        </div>
        <br><br><br><br><br><br><br>
      </form>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

{% block scripts %}
<script>
  $('#qp-btn').click(() => {
    $('#qp-panels').show();
    $('#qp2-panels').hide();
  });

  $('#qp2-btn').click(() => {
    $('#qp-panels').hide();
    $('#qp2-panels').show();
  });

  $('#all-btn').click(() => {
    $('#qp-panels').show();
    $('#qp2-panels').show();
  });
</script>
{% endblock %}