dashboard/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='dashboard'),
    path('scoring/', views.scoring, name='scoring'),
    path('scoring/<int:appid>', views.score_applicant, name='score_applicant'),
    path('rubric/', views.rubric, name='rubric'),
    path('teams/', views.teams, name='teams'),
    path('teams/<int:teamid>', views.specific_team, name='specific_team'),
    path('mentors/', views.mentors, name='mentors'),
    path('proposal/', views.ProjectProposalCreate.as_view(), name='proposal'),
    path('documentation/success/', views.documentation_success, name='documentation_success'),
    path('milestones/', views.MilestoneCreate.as_view(), name='milestone'),
    path('workshops/', views.workshops, name='workshop'),
    path('calendar/', views.calendar, name="calendar"),
]

ieeeqpucsd/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('ieeeqpadmin/', admin.site.urls),
    path('', include('landing.urls')),
    path('dashboard/', include('dashboard.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

landing/urls.py
from django.urls import path
from . import views
from datetime import date

deadline = date(2020, 1, 15)
today = date.today()

if (today >= deadline):
    application_view = views.apply_closed
else:
    application_view = views.QPApplicationCreate.as_view()

urlpatterns = [
    path('', views.index, name='index'),
    path('apply/', application_view, name='apply'),
    path('success/', views.apply_success, name='apply-success'),
    path('login/', views.login_view, name='login'),
    path('ieeeqpsignup/', views.register_view, name='register'),
    path('logout/', views.logout_view, name='logout'),
    # path('.well-known/acme-challenge/579nh20yWm02orHMdz28CwPMtC8QWlMOjNEjIz8b9T4/', views.https_view, name='https'),
]

landing/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from datetime import date
from gdstorage.storage import GoogleDriveStorage, GoogleDrivePermissionType, GoogleDrivePermissionRole, GoogleDriveFilePermission
from django.core.validators import MaxValueValidator, MinValueValidator
import json

permission = GoogleDriveFilePermission(
   GoogleDrivePermissionRole.READER,
   GoogleDrivePermissionType.USER,
   "foo@mailinator.com"
)

gd_storage = GoogleDriveStorage()

class team(models.Model):
    name = models.CharField(max_length=100)
    nickname = models.CharField(max_length=100)
    members = models.CharField(null=True, blank=True, max_length=200)
    mentor = models.ForeignKey(User, null=True, blank=True, on_delete=models.DO_NOTHING)

    class Meta:
        ordering = ['nickname', 'name']
        permissions = (
            ('can_create_team', 'Can Create Team'),
        )

    def set_members(self, arr):
        self.members = json.dumps(arr)

    def get_members(self):
        return json.loads(self.members)


class QPApplication(models.Model):
    """Model representing a single QP application."""
    score = models.IntegerField(null=True, default=0, validators=[MaxValueValidator(10), MinValueValidator(0)])

    num_of_scores = models.IntegerField(null=True, default=0, help_text="# of scorers")

    first_name = models.CharField(max_length=100, help_text="First Name *")

    last_name = models.CharField(max_length=100, help_text="Last Name *")

    email = models.EmailField(max_length=100, help_text="Email *")

    personal_link = models.URLField(null=True, blank=True, help_text="Link to personal website, portfolio or Github", max_length=200)

    PROGRAM_CHOICES = (
        ('qp', 'Quarterly Projects'),
        ('qp2', 'QP++'),
        ('bo', 'Both')
    )

    programs = models.CharField(
        max_length=50,
        choices=PROGRAM_CHOICES,
        default='qp',
        help_text='Which programs would you like to be considered for? *',
    )

    DEPARTMENT_CHOICES = (
        ('ece', 'Electrical and Computer Engineering'),
        ('cse', 'Computer Science and Engineering'),
        ('mae', 'Mechanical and Aerospace Engineering'),
        ('be', 'BioEngineering'),
        ('ne', 'NanoEngineering'),
        ('se', 'Structural Engineering'),
        ('cs', 'Cognitive Science'),
        ('ds', 'Data Science'),
        ('math', 'Mathematics'),
        ('bs', 'Biological Sciences'),
        ('candb', 'Chemistry & Biochemistry'),
        ('p', 'Physics'),
        ('bus', 'Business'),
        ('hum', 'Humanities'),
        ('oth', 'Other'),
    )

    department = models.CharField(
        max_length=100,
        choices=DEPARTMENT_CHOICES,
        default='ece',
        help_text='Select your department *',
    )

    YEAR_OF_STUDY_CHOICES = (
        ('fr', 'Freshman'),
        ('so', 'Sophomore'),
        ('ju', 'Junior'),
        ('se', 'Senior'),
        ('oth', 'Other'),
    )

    year_of_study = models.CharField(
        max_length=20,
        choices=YEAR_OF_STUDY_CHOICES,
        default='fr',
        help_text='Year of Study *'
    )

    HOW_DID_YOU_HEAR_CHOICES = (
        ('gbm', 'IEEE GBM'),
        ('fb', 'Facebook'),
        ('news', 'Newsletter'),
        ('fly', 'Flyer'),
        ('ta', 'Tabling (Engineers on the Green, Library Walk, etc.)'),
        ('fr', 'Friend in IEEE UC San Diego'),
        ('pr', 'Previously in IEEE Quarterly Projects'),
        ('oth', 'Other'),
    )

    how_did_you_hear = models.CharField(
        max_length=100,
        choices=HOW_DID_YOU_HEAR_CHOICES,
        default='gbm',
        help_text='How did you hear about Quarterly Projects? *',
    )

    course_work = models.TextField(
        max_length=1500, help_text='List any coursework relevant to building projects or working in teams! *')

    extracurricular_work = models.TextField(
        max_length=3000, help_text='List and describe up to 3 extracurricular projects or experiences *')

    technical_skills = models.TextField(
        max_length=1000, help_text='List any technical skills you have with a rating from 1 to 5 (eg: Photoshop (5),  AutoCAD (4), Python (3), Excel (1), etc.) *')
    
    MICROCONTROLLER_CHOICES = (
        ('y', 'Yes'),
        ('n', 'No'),
    )

    microcontrollers = models.CharField(
        max_length=3,
        choices=MICROCONTROLLER_CHOICES,
        default='y',
        help_text='Have you used microcontrollers before (Raspberry Pi, Arduino, STM, etc)? *',
    )

    collab_situation = models.TextField(
        max_length=3000, help_text='Describe a situation where you collaborated with others *')

    project_motivation = models.TextField(
        max_length=1000, help_text='In one to two sentences, what motivates you to be on a project? Why do you want to build a project, and what benefit does project experience bring to you and your teammates? *')

    project_goal_but_not_steps = models.TextField(
        max_length=3000, help_text='Imagine that you know the goal of your project but are unsure of the intermediate steps necessary to achieve it. What would you do to figure out these intermediate steps in order to progress and finish your project? *')

    rude_team_member = models.TextField(
        max_length=3000, help_text='You have a team member that is rude to your team members, does little work, and is in general hard to work with. How do you address this? *')

    QUARTER_LONG_CHOICES = (
        ('y', 'Yes'),
    )

    quarter_long_obligation = models.CharField(
        max_length=3,
        choices=QUARTER_LONG_CHOICES,
        default='n',
        help_text='I understand that this is a quarter long obligation and that not showcasing my project will negatively impact my team. *',
    )

    teammates = models.TextField(null=True, blank=True,
        max_length=1000, help_text='Hoping to work with other people? Please list their full name, email and major. (eg: John Smith, jsmith@gmail.com, ECE)')

    # resume_upload = models.FileField(null=True, blank=True, upload_to='resumes/', storage=gd_storage, help_text='Please upload your resume in "firstname_lastname_CV.pdf" format')

    team = models.ForeignKey(team, null=True, on_delete=models.SET_NULL)

    accepted = models.BooleanField(default=False)
    
    class Meta:
        ordering = ['-score']
        permissions = (
            ('can_score_applicant', 'Can Score Application'),
        )

    def clean(self):
        if self.score is None:
            self.score = 0
        if self.num_of_scores is None:
            self.num_of_scores = 0

dashboard/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from landing.models import QPApplication, team
from dashboard.models import ScoreApplication, ProjectProposal, Milestone
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from ieeeqpucsd import settings
from itertools import chain
from . import forms
import os

# @login_required
def index(request):
    return render(request, 'dashboard.html', context={})

#(LoginRequiredMixin, CreateView)
class ProjectProposalCreate(CreateView):
    model = ProjectProposal
    form_class = forms.ProjectProposalForm

    def get_success_url(self):
        return reverse('documentation_success')

    def get_context_data(self, **kwargs):
        ctx = super(ProjectProposalCreate, self).get_context_data(**kwargs)
        ctx['proposals_qp'] = ProjectProposal.objects.filter(program="qp").order_by('id')
        ctx['proposals_qp2'] = ProjectProposal.objects.filter(program="qp2").order_by('id')
        return ctx

#(LoginRequiredMixin, CreateView)
class MilestoneCreate(CreateView):
    model = Milestone
    form_class = forms.MilestoneReportForm

    def get_success_url(self):
        return reverse('documentation_success')

    def get_context_data(self, **kwargs):
        ctx = super(MilestoneCreate, self).get_context_data(**kwargs)
        ctx['milestone_1'] = Milestone.objects.filter(report_num='1').order_by('id')
        ctx['milestone_2'] = Milestone.objects.filter(report_num='2').order_by('id')
        return ctx

# @login_required
def documentation_success(request):
    return render(request, 'documentation_success.html', context={})

# @login_required
@user_passes_test(lambda u: u.has_perm('landing.can_score_applicant'))
def scoring(request):
    existing_ids = ScoreApplication.objects.filter(scorer_id=request.user.id).values_list('application_id', flat=True)
    existing_apps = QPApplication.objects.filter(id__in=existing_ids)
    unscored_apps = QPApplication.objects.exclude(id__in=existing_ids)

    context={
        'unscored_apps': unscored_apps,
        'existing_apps': existing_apps,
        'all_apps': QPApplication.objects.all().count,
    }
    return render(request, 'scoring.html', context)

# @login_required
@user_passes_test(lambda u: u.has_perm('landing.can_score_applicant'))
def rubric(request):
    return render(request, 'dash_rubric.html', context={})

# @login_required
@user_passes_test(lambda u: u.has_perm('landing.can_score_applicant'))
def score_applicant(request, appid):
    instance = get_object_or_404(QPApplication, id=appid)
    existing = ScoreApplication.objects.filter(scorer_id=request.user.id, application_id=instance.id)
    check_existing = existing and existing.count() > 0

    if request.method == "POST":
        update_form = forms.UpdateQPApplication(request.POST, instance=instance)
        score_form = forms.ScoreApplicationForm(request.POST)
        safe_num_scores = instance.num_of_scores if instance.num_of_scores else 0
        safe_score = instance.score if instance.score else 0

        if score_form.is_valid() and update_form.is_valid():
            post_score = score_form.save(commit=False)
            post_application = update_form.save(commit=False)
            post_score.application_id = instance.id
            post_score.scorer_id = request.user.id
            post_application.num_of_scores = safe_num_scores + 1
            cleaned_score = score_form.cleaned_data.get('score')
            cleaned_accept = update_form.cleaned_data.get('accepted')
            post_application.score = cleaned_score + safe_score
            if (cleaned_accept):
                post_application.accepted = cleaned_accept
            else:
                post_application.accepted = instance.accepted
            post_score.save()
            post_application.save()
            return redirect('scoring')
        
        if not score_form.is_valid() and update_form.is_valid():
            update_form.save()
    
    else:
        update_form = forms.UpdateQPApplication(instance=instance)
        score_form = forms.ScoreApplicationForm()

    context={
        'applicant': instance,
        'score_form': score_form,
        'update_form': update_form,
        'check_existing': check_existing,
    }

    return render(request, 'score_applicant.html', context)

@login_required
def teams(request):
    if request.method == "POST":
        create_team = forms.CreateTeamForm(request.POST)
        if create_team.is_valid():
            cleaned_members = create_team.cleaned_data['member_choices']
            custom_saved_members = create_team.customSave()

            for member in cleaned_members:
                app_instance = get_object_or_404(QPApplication, id=member.id)
                update_form = forms.UpdateQPApplication(request.POST, instance=app_instance)
                post_application = update_form.save(commit=False)
                post_application.team_id = custom_saved_members.pk
                post_application.accepted=1
                post_application.save()

            return redirect('teams')
    else:
        create_team = forms.CreateTeamForm()
    
    qpteams = {}
    qp2teams = {}
    
    context = {
        'create_team': create_team,
        'qpteams': team.objects.filter(nickname="QP").order_by('id'),
        'qp2teams': team.objects.filter(nickname="QP++").order_by('id'),
    }

    return render(request, 'teams.html', context)

@login_required
def specific_team(request, teamid):
    # Get specific team using id
    team_instance = get_object_or_404(team, id=teamid)

    # Backfilling
    backfill_members = team_instance.members.replace("['", "").replace("']", "").split("', '")

    # Assign team id to each person on team
    for member in backfill_members:
        name = member.split(" ", 1)
        person = QPApplication.objects.filter(first_name=name[0]).filter(last_name=name[1]).first()
        update_form = forms.UpdateQPApplication(request.POST, instance=person)
        post_application = update_form.save(commit=False)
        post_application.team_id = teamid
        post_application.accepted = 1
        post_application.save()

    # Get QPApplicant
    members = QPApplication.objects.filter(team_id=teamid)

    # Get mentor
    mentor = User.objects.filter(id=team_instance.mentor_id)

    # get email
    emails = members.values('email')

    # list of emails
    team_emails = {}
    for i in range(0, len(emails)):
        team_emails[members[i].first_name + ' ' + members[i].last_name] = emails[i]['email']

    context = {
        'team': team_instance,
        'team_emails': team_emails,
        'mentor': mentor,
    }
    return render(request, 'specific_team.html', context)


# @login_required
def mentors(request):
    image_list=[]
    email_list={}
    for root, dirs, files in os.walk(settings.STATIC_ROOT):
        for file in files:
            staticUrl = 'staff/'
            if file.endswith("_mentor.jpg"):
                mentor = User.objects.filter(first_name=file.replace("_mentor.jpg", ""))
                email = mentor.values_list('email', flat=True)
                name = mentor.values_list('first_name', flat=True)
                for i in range(0, len(email)):
                    email_list[name[i]] = email[i]

                staticUrl += file
                image_list.append(staticUrl)
    
    row1 = image_list[0: len(image_list)//4]
    row2 = image_list[len(image_list)//4: len(image_list)//2]
    row3 = image_list[len(image_list)//2: len(image_list)*3//4]
    row4 = image_list[len(image_list)*3//4: len(image_list)]

    return render(request, 'mentors.html', context={ 'row1': row1, 'row2': row2, 'row3': row3, 'row4': row4, 'emails': email_list })

@login_required
def calendar(request):
    return render(request, 'calendar.html', context={})

# @login_required
def workshops(request):
    return render(request, 'workshops.html', context={})

dashboard/templates/calendar.html
{% extends 'dash_generic.html' %}
{% block body %}
<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
    <div class="row">
        <ol class="breadcrumb">
            <li><a href="/dashboard">
                    <em class="fa fa-home"></em>
                </a></li>
            <li class="active">Schedule</li>
        </ol>
    </div>

    <div class="row">
        <div class="col-lg-12 text-center">
            <div class="my-header-row" style="justify-content: space-between;">
                <h1 class="page-header" style="padding: 0;">IEEE QP Fall Calendar</h1>
            </div>
            <iframe
                src="https://calendar.google.com/calendar/embed?src=ucsd.edu_7mrh7jd7j7v58h114rpmrs90jo%40group.calendar.google.com&ctz=America%2FLos_Angeles"
                style="border: 0" width="100%" height="600" frameborder="0" scrolling="no"></iframe>
        </div>
    </div>

    <br><br>
</div>
{% endblock %}

{% block scripts %}

{% endblock %}

dashboard/templates/dash_generic.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block title %}<title>IEEE Quarterly Projects</title>{% endblock %}

    {% load static %}

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/datepicker3.css' %}" rel="stylesheet">
    <link href="{% static 'css/dashstyle.css' %}" rel="stylesheet">
    <link href="{% static 'css/mydash.css' %}" rel="stylesheet">

    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/favicon_io/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/favicon_io/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicon_io/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'images/favicon_io/site.webmanifest' %}">

    <!--Custom Font-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,300i,400,400i,500,500i,600,600i,700,700i"
        rel="stylesheet">
    <!--[if lt IE 9]>
	<script src="js/html5shiv.js"></script>
	<script src="js/respond.min.js"></script>
	<![endif]-->
</head>

<body>
    {% include 'dash_topnav.html' %}
    {% block body %}{% endblock %}
    {% load static %}
    <script src="{% static 'js/jquery-1.11.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/chart.min.js' %}"></script>
    <script src="{% static 'js/chart-data.js' %}"></script>
    <script src="{% static 'js/easypiechart.js' %}"></script>
    <script src="{% static 'js/easypiechart-data.js' %}"></script>
    <script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
    <script src="{% static 'js/custom.js' %}"></script>
    {% block scripts %}{% endblock %}
</body>

</html>

dashboard/templates/documentation_success.html
{% extends 'dash_generic.html' %}
{% block body %}
<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
    <div class="row">
        <ol class="breadcrumb">
            <li><a href="/dashboard">
                    <em class="fa fa-home"></em>
                </a></li>
            <li class="active">Upload Success</li>
        </ol>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <h1>Thank you for submitting! You're submission was processed successfully. Please contact your mentor or
                the IEEE QP Chairs if you have any questions!</h1>
        </div>
    </div>
</div>
{% endblock %}

dashboard/templates/score_applicant.html
{% extends 'dash_generic.html' %}
{% block body %}
<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
    <div class="row">
        <ol class="breadcrumb">
            <li><a href="/dashboard">
                    <em class="fa fa-home"></em>
                </a></li>
            <li class="active"><a style="text-decoration: none; color: #777777;" href="/dashboard/scoring">
                    Scoring</em>
                </a></li>
            <li class="active">{{ applicant.id }}</li>
        </ol>
    </div>
    <br>
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-blue">
                <div class="panel-heading dark-overlay">{{ applicant.first_name }} {{ applicant.last_name }}</div>
                <div class="panel-body">
                    <div class="col-md-4">
                        <div class="panel panel-teal">
                            <div class="panel-heading dark-overlay">Year</div>
                            <div class="panel-body">
                                {{ applicant.get_year_of_study_display }}
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="panel panel-teal">
                            <div class="panel-heading dark-overlay">Department</div>
                            <div class="panel-body">
                                {{ applicant.get_department_display }}
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="panel panel-teal">
                            <div class="panel-heading dark-overlay">Program(s)</div>
                            <div class="panel-body">
                                {{ applicant.get_programs_display }}
                            </div>
                        </div>
                    </div>

                    <div class="col-md-12">
                        <div class="panel panel-teal">
                            <div class="panel-heading dark-overlay">Link to Portfolio</div>
                            <div class="panel-body custom-white-panel">
                                {% if applicant.teammates %}{{ applicant.personal_link }}{% else %}None{% endif %}
                            </div>
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="panel panel-teal">
                            <div class="panel-heading dark-overlay">Technical Skills</div>
                            <div class="panel-body custom-white-panel">
                                {{ applicant.technical_skills }}
                            </div>
                        </div>
                        <div class="panel panel-teal">
                            <div class="panel-heading dark-overlay">Used Microcontrollers?</div>
                            <div class="panel-body custom-white-panel">
                                {{ applicant.get_microcontrollers_display }}
                            </div>
                        </div>
                        <div class="panel panel-teal">
                            <div class="panel-heading dark-overlay">Coursework</div>
                            <div class="panel-body custom-white-panel">
                                {{ applicant.course_work }}
                            </div>
                        </div>

                        <div class="panel panel-teal">
                            <div class="panel-heading dark-overlay">My Motivation</div>
                            <div class="panel-body custom-white-panel">
                                {{ applicant.project_motivation }}
                            </div>
                        </div>
                        <div class="panel panel-teal">
                            <div class="panel-heading dark-overlay">I know the goal but not the steps!</div>
                            <div class="panel-body custom-white-panel">
                                {{ applicant.project_goal_but_not_steps }}
                            </div>
                        </div>
                        <div class="panel panel-teal">
                            <div class="panel-heading dark-overlay">Teammates</div>
                            <div class="panel-body custom-white-panel">

                                {% if applicant.teammates %}{{ applicant.teammates }}{% else %}None{% endif %}
                            </div>
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="panel panel-teal">
                            <div class="panel-heading dark-overlay">Extracurricular</div>
                            <div class="panel-body custom-white-panel">
                                {{ applicant.extracurricular_work }}
                            </div>
                        </div>

                        <div class="panel panel-teal">
                            <div class="panel-heading dark-overlay">Example of Collaboration</div>
                            <div class="panel-body custom-white-panel">
                                {{ applicant.collab_situation }}
                            </div>
                        </div>
                        <div class="panel panel-teal">
                            <div class="panel-heading dark-overlay">Rude Teammates</div>
                            <div class="panel-body custom-white-panel">
                                {{ applicant.rude_team_member }}
                            </div>
                        </div>
                        <div class="custom-input-panel">
                            <form method="post" class="form-inline" id="target">
                                {% csrf_token %}
                                {% if check_existing %}
                                <div>You already scored this applicant!</div>
                                {% elif applicant.num_of_scores > 4 %}
                                <div>This applicant has already been scored 5 times!</div>
                                {% else %}
                                {% for field in score_form %}
                                {{ field.errors }}
                                <label>Score (1 - 10): <a style="color: white; text-decoration: underline;"
                                        href="/dashboard/rubric">Read Rubric First</a>
                                </label>
                                <div class="custom-input-panel-text">
                                    {{ field }}
                                    {% if field.help_text %}
                                    <p class="help">{{ field.help_text|safe }}</p>
                                    {% endif %}
                                    <div class="col-auto my-1">
                                        <button type="submit" class="btn btn-info">Submit</button>
                                    </div>
                                </div>
                                {% endfor %}
                                {% endif %}
                                <br>
                                {% for field in update_form %}
                                <div
                                    style="display: flex; flex-direction: row; justify-content: space-evenly; align-items: center;">
                                    <label {% if not request.user.is_staff %} style="display: none;" {% endif %}>Accept
                                        applicant?</label>
                                    <div {% if not request.user.is_staff %} style="display: none;" {% endif %}
                                        class="custom-input-panel-text">
                                        <div style="display: none;">{{ field }}</div>
                                        <button type="button"
                                            class="btn btn-info {% if applicant.accepted %} disabled {% endif %}"
                                            id="accept-btn">{% if applicant.accepted %}&#10004;{% else %}Accept{% endif %}</button>
                                    </div>
                                </div>
                                {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script>
    $('#accept-btn').click(() => {
        if (!$('#accept-btn').hasClass('disabled')) {
            $('#accept-btn').addClass('disabled');
            $('#accept-btn').addClass('btn-primary');
            $('#accept-btn').html('&#10004;')
            $('input:checkbox').prop('checked', true);
            $('#target').submit();
        }
    });
</script>
{% endblock %}